### ISSUE TITLE
Having problems to build on Solaris2.8/2.9

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#11]
gcc -c  -I.. -I. -I/usr/local/include   -I/usr/include/X11 -
g -
DINSTPATH=\&quot;/home/se046969/bragrej/modules/appmodu
le\&quot; ModuleCmd_Avail.c
In file included from /usr/local/lib/gcc-lib/sparc-sun-
solaris2.4/2.7.2.2/include/time.h:90,
                 from ModuleCmd_Avail.c:44:
/usr/include/sys/siginfo.h:74: parse error before 
`pthread_attr_t'
/usr/include/sys/siginfo.h:74: warning: no semicolon at 
end of struct or union
/usr/include/sys/siginfo.h:76: parse error before `}'
In file included from /usr/local/lib/gcc-lib/sparc-sun-
solaris2.4/2.7.2.2/include/time.h:90,
                 from ModuleCmd_Avail.c:44:
/usr/include/sys/siginfo.h:284: parse error before 
`int32_t'
/usr/include/sys/siginfo.h:284: warning: no semicolon at 
end of struct or union
/usr/include/sys/siginfo.h:284: warning: no semicolon at 
end of struct or union
/usr/include/sys/siginfo.h:286: parse error before `}'
/usr/include/sys/siginfo.h:286: warning: data definition 
has no type or storage class
/usr/include/sys/siginfo.h:288: parse error before `}'
/usr/include/sys/siginfo.h:288: warning: data definition 
has no type or storage class
/usr/include/sys/siginfo.h:415: parse error before 
`int32_t'
/usr/include/sys/siginfo.h:415: warning: no semicolon at 
end of struct or union
/usr/include/sys/siginfo.h:415: warning: no semicolon at 
end of struct or union
/usr/include/sys/siginfo.h:416: conflicting types for 
`__rctl'
/usr/include/sys/siginfo.h:285: previous declaration of 
`__rctl'
/usr/include/sys/siginfo.h:418: parse error before `}'
/usr/include/sys/siginfo.h:418: warning: data definition 
has no type or storage class
/usr/include/sys/siginfo.h:420: parse error before `}'
/usr/include/sys/siginfo.h:420: warning: data definition 
has no type or storage class
/usr/include/sys/siginfo.h:424: parse error before 
`k_siginfo_t'
/usr/include/sys/siginfo.h:424: warning: no semicolon at 
end of struct or union
/usr/include/sys/siginfo.h:428: parse error before `}'
/usr/include/sys/siginfo.h:428: warning: data definition 
has no type or storage class
*** Error code 1
make: Fatal error: Command failed for target 
`ModuleCmd_Avail.o'

Reported by: qrabenj
